# Generated by Django 4.2.3 on 2023-08-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'ordering': ['account_no']},
        ),
    ]
